<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Base.Contracts.BLL\Base.Contracts.BLL.csproj" />
      <ProjectReference Include="..\BLL.App.DTO\BLL.App.DTO.csproj" />
      <ProjectReference Include="..\DAL.App.Contracts\DAL.App.Contracts.csproj" />
    </ItemGroup>

</Project>
