import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/nav/MainNav";
import { Container, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import theme from "@/components/Theme";
import SideNav from "@/components/nav/SideNav";
import AppState from "@/components/AppState";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/*<Container sx={{ height: '100vh', background:'#E9F1FA'}}>    
            </Container>*/
//npm install @dnd-kit/core
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AppState>
                <MainNav/>
                  {children}
            </AppState>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
