<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <UserSecretsId>aspnet-WebApp-9680CAA5-FD7C-40CD-980A-3538EEE1C7B3</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.3" />
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DAL.App.EF\DAL.App.EF.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Prices\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Prices\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Prices\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Prices\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Prices\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Supplys\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Supplys\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Supplys\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Supplys\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Supplys\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Teams\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Teams\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Teams\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Teams\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Teams\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_LoginPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserNotifications\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserNotifications\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserNotifications\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserNotifications\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserNotifications\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserTeams\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserTeams\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserTeams\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserTeams\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\UserTeams\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ProductionMetas\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ProductionMetas\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ProductionMetas\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ProductionMetas\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ProductionMetas\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Warehouse\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Warehouse\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Warehouse\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Warehouse\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Warehouse\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Productions\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Productions\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Productions\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Productions\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Productions\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\OrderDatas\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\OrderDatas\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\OrderDatas\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\OrderDatas\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\OrderDatas\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Orders\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Orders\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Orders\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Orders\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Orders\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\NotificationTypes\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\NotificationTypes\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\NotificationTypes\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\NotificationTypes\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\NotificationTypes\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Items\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Items\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Items\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Items\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Items\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ItemComponents\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ItemComponents\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ItemComponents\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ItemComponents\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ItemComponents\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Customers\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Customers\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Customers\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Customers\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Customers\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Components\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Components\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Components\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Components\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Components\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ActiveNotifications\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ActiveNotifications\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ActiveNotifications\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ActiveNotifications\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\ActiveNotifications\Index.cshtml" />
    </ItemGroup>

</Project>
