<Project Sdk="Microsoft.NET.Sdk.Web">
    
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-WebApp-B61743E7-A12C-43D8-9911-84951021B202</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.2" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="6.0.2" />
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DAL.App.EF\DAL.App.EF.csproj" />
      <ProjectReference Include="..\DAL.App\DAL.App.csproj" />
      <ProjectReference Include="..\Extensions.Base\Extensions.Base.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas\Admin" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Address\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Address\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Address\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Address\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Address\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Customer\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Customer\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Customer\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Customer\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Customer\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\ItemProcedure\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\ItemProcedure\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\ItemProcedure\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\ItemProcedure\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\ItemProcedure\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Process\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Process\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Process\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Process\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Process\Index.cshtml" />
    </ItemGroup>

</Project>
